// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: prototype.proto

/* eslint-disable */

export const protobufPackage = "";

export enum ProtocolType {
  None = 0,
  LOGIN_REQUEST = 10001,
  LOGIN_RESPONSE = 10002,
  CHAT_NOTIFY = 10003,
  CHAT_REQUEST = 10004,
  CHAT_RESPONSE = 10005,
  UNRECOGNIZED = -1,
}

export function protocolTypeFromJSON(object: any): ProtocolType {
  switch (object) {
    case 0:
    case "None":
      return ProtocolType.None;
    case 10001:
    case "LOGIN_REQUEST":
      return ProtocolType.LOGIN_REQUEST;
    case 10002:
    case "LOGIN_RESPONSE":
      return ProtocolType.LOGIN_RESPONSE;
    case 10003:
    case "CHAT_NOTIFY":
      return ProtocolType.CHAT_NOTIFY;
    case 10004:
    case "CHAT_REQUEST":
      return ProtocolType.CHAT_REQUEST;
    case 10005:
    case "CHAT_RESPONSE":
      return ProtocolType.CHAT_RESPONSE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProtocolType.UNRECOGNIZED;
  }
}

export function protocolTypeToJSON(object: ProtocolType): string {
  switch (object) {
    case ProtocolType.None:
      return "None";
    case ProtocolType.LOGIN_REQUEST:
      return "LOGIN_REQUEST";
    case ProtocolType.LOGIN_RESPONSE:
      return "LOGIN_RESPONSE";
    case ProtocolType.CHAT_NOTIFY:
      return "CHAT_NOTIFY";
    case ProtocolType.CHAT_REQUEST:
      return "CHAT_REQUEST";
    case ProtocolType.CHAT_RESPONSE:
      return "CHAT_RESPONSE";
    case ProtocolType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
